# Generated by Django 5.1.1 on 2024-12-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0002_initial'),
        ('reservas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='arrendatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.arrendatario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.propiedad'),
        ),
    ]
