apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: django-app
        image: vicmah/django_api:latest
        command: ["/bin/sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]
        env:
        - name: FRONTEND_URL_MANIFEST
          value: "http://35.184.196.156"
        - name: DEBUG
          value: "1"
        - name: SECRET_KEY
          value: "your-secret-key"
        - name: DJANGO_SETTINGS_MODULE
          value: "cocoonbackend.settings"
        - name: DATABASE_URL
          value: "postgres://django_user:1234ch@db:5432/django_db"
        volumeMounts:
        - name: static-volume
          mountPath: /app/staticfiles
        # - name: media-volume
        #   mountPath: /app/media
        ports:
        - containerPort: 8000
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-volume
      # - name: media-volume
      #   persistentVolumeClaim:
      #     claimName: media-volume
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
